const bingoItems = [
    "Missed interrupt",
    "Healer doesn't click during memory game",
    "Streamer glaive death",
    "“It's facing the wrong way”",
    "Starsplinter snipes a crystal",
    "Mispositioned in intermission",
    "Someone picks up a crystal in P2 by accident",
    "Someone gets bowling balled in P2",
    "Failed P3 memory game",
    "Crystal carrier gets hit by constellation",
    "Someone forgets to drop crystal in P3",
    "Tank forgets to hit extra action button in P4",
    "Starsplinter terrorist",
    "Sub 2% wipe",
    "Someone mistakes diamond for triangle",
    "“Kill or disband”",
    "RL crashout",
    "P3/P4 ad break",
    "Streamer crashout",
    "Someone ends the pull at 269k DPS/HPS",
    "1000+ pull count",
    "Crystal soak gets missed",
    "Streamer does P4 practice tool",
    "Crazy comp",
    "Failed P3 soak",
    "Streamer dies to constellation",
    "Streamer falls behind P4 run",
    "Movement speed is forgotten for P4 run",
    "Nerd screams P3/P4",
    "Kill with 3 or less alive",
    "Inspirational speech",
    "Missing 3+ raid buffs",
    "Bar button clicker (memory game excluded)"
];
