const bingoItems = [
    "Tank forgets to hit extra action button in P4",
    "Failed P3 soak",
    "Someone mistakes diamond for triangle",
    "Failed P3 memory game",
    "Someone forgets to drop crystal in P3",
    "Starsplinter terrorist",
    "Streamer dies to constellation",
    "Streamer falls behind P4 run",
    "Movement speed is forgotten for P4 run",
    "Sub 1% wipe",
    "“Kill or disband”",
    "RL crashout",
    "Nerd screams P3/P4",
    "Ad break",
    "Streamer crashout",
    "Someone ends the pull at 269k DPS/HPS",
    "Kill with 3 or less alive",
    "1000+ pull count",
    "Inspirational speech",
    "Streamer glaive death",
    "Crystal soak gets missed",
    "Streamer does P4 practice tool",
    "Missing 3+ raid buffs",
    "Bar button clicker (memory game excluded)",
    "LURA DIES"
];
